
#--------[ starship_theLine_MINIMAL ]

format = """
${custom.directory}\
$git_branch\
$git_status\
[ |](fg:#ED333B bg:#2E2F38)\
[ ]()\

"""

#--------[COMMANDS]

[custom.directory]
description = "Replace the default directory command"
command = """echo "${PWD/$HOME/~}" """
style = "fg:#33dd2d bg:#2E2F38"
format = "[  󰉋 $output ]($style)"
when = "true"

#--------[GIT COMMANDS]

[git_branch]
symbol = " "
style = "fg:#e5e512 bg:#242424"
format = "[ $symbol$branch(:$remote_branch) ]($style)"

[git_status]
# disabled = true
style = "fg:#e5e512 bg:#242424"
staged = "STG:${count} " # nf-fa-check
modified = "MOD:${count} " # nf-fa-edit
# modified = "  ${count}" # nf-fa-pencil
renamed = "󰗧:${count} " # nf-md-cursor_text
untracked = "UN:${count} " # nf-fa-question
deleted = "DEL:${count} " # nf-fa-remove
conflicted = "✖:${count} " # nf-fa-flag
stashed = ":${count} " # nf-fa-bank
# stashed = "  ${count}" # nf-fa-inbox

ahead = "󰞙 ${count} " # nf-md-arrow_expand_up
behind = "󰞖 ${count} " # nf-md-arrow_expand_down
diverged = "󰡏 ${ahead_count} ${behind_count} " # nf-md-arrow_expand_vertical
# diverged = "󰯎 ${ahead_count} ${behind_count}" # nf-md-swap_vertical_bold
# ignore_submodules = true
format = "[ ([$staged](fg:47 bg:#242424)[$modified](fg:5 bg:#242424)$renamed[$untracked](blue bg:#242424)[$deleted](fg:9 bg:#242424)$conflicted$stashed$ahead_behind )]($style)"

[git_state]
# disabled = true
style = "bg:color_git_state fg:color_foreground_dark"
rebase = "rebasing"
merge = "merging"
revert = "reverting"
cherry_pick = " picking" # nf-fae-cherry
bisect = "bisecting"
am = "am'ing"
am_or_rebase = "am/rebase"
format = '[ $state($progress_current/$progress_total) ]($style)'
